
    - name: Install Java
      package: name=java-1.8.0-openjdk state=present
      notify: Handler one

    - name: Flush Handlers # make handler execute immediately, otherwise the handler will wait until the end to run
      meta: flush_handlers

    - name: Download Solr.
      get_url:
        url: "https://archive.apache.org/dist/lucene/solr/{{ solr_version }}/solr-{{ solr_version }}.tgz"
        dest: "{{ download_dir }}/solr-{{ solr_version }}.tgz"
        checksum: "{{ solr_checksum }}"
      notify: Handler two # must have the right name of the handler to be called, otherwise will throw error 
      # environment: # inside this task only
      #   http_proxy: something.com:80 

    - name: Flush Handlers
      meta: flush_handlers

    - name: Expand Solr.
      notify: Handler one
      unarchive:
        src: "{{ download_dir }}/solr-{{ solr_version }}.tgz"
        dest: "{{ download_dir }}"
        remote_src: true
        creates: "{{ download_dir }}/solr-{{ solr_version }}/README.txt"

    - name: Flush Handlers
      meta: flush_handlers

    - name: Run Solr installation script.
      notify: Handler two
      command: >
        {{ download_dir }}/solr-{{ solr_version }}/bin/install_solr_service.sh
        {{ download_dir }}/solr-{{ solr_version }}.tgz
        -i /opt
        -d /var/solr
        -u solr
        -s solr
        -p 8983
        creates={{ solr_dir }}/bin/solr
      
      ignore_errors: True

    - name: Flush Handlers
      meta: flush_handlers

    - name: Ensure solr is started and enabled on boot.
      service: name=solr state=started enabled=yes
      notify: Handler one

    - name: Flush Handlers
      meta: flush_handlers