# dash ("-") means: things in *array*
- hosts: all
  become: yes # -b: (default) become superuser
  tasks:
    - name: Ensure NTP is installed.
      yum: name=ntp state=present
    #- commend: echo Hello World
    #- shell: echo Nihaoma
    - name: Ensure NTP is running.
      service: name=ntpd state=started enabled=yes
    
    - name: Install Apache
      command: yum install -y --quiet httpd httpd-devel

    - name: Install Apache
      yum: 
        name:
          - httpd
          - httpd-devel
        state: present

    - name: Copy configuration files.
      command: cp /etc/httpd/conf/httpd.conf httpd.conf
    #- command: cp httpd-vhosts.conf /etc/httpd/conf/httpd-vhosts.conf

    - name: Copy configuration files.
      copy:
        src: "{{ item.src }}" # or, "{{ item['src'] }}"
        dest: "{{ item.dest }}"
        remote_src: yes
        owner: root
        group: root
        mode: 0644
      with_items:
        - dest: httpd.conf
          src: /etc/httpd/conf/httpd.conf
        #- src: httpd-vhosts.conf
        #  dest: /etc/httpd/conf/httpd-vhosts.conf

    - name: Start Apache and configure it to run at boot
      command: service httpd start

    - name: Start Apache and configure it to run at boot
      service: 
        name: httpd
        state: started
        enabled: true # or ... (yes), either way. Use 0/1 may get datatype mismatch error
        
    - command: chkconfig httpd on

