- hosts: all
  become: yes
  tasks:
    - name: Ensure NTP is installed.
      yum: name=ntp state=present
    #- commend: echo Hello World
    #- shell: echo Nihaoma
    - name: Ensure NTP is running.
      service: name=ntpd state=started enabled=yes