# dash ("-") means: things in *array*
# otherwise, it is attribute 
- hosts: all
  become: yes # -b: (default) become superuser
  vars_files:
    - vars.yml
  pre_tasks:
    - name: Update yum cache if needed
      command: "yum makecache"
      
  handlers: # runs if has "change" and has "notify"
    - name: Restart solr
      command: echo "Freddie you called the handler!!!"

  tasks:
    - name: Install Java
      package: name=java-1.8.0-openjdk state=present

    - name: Download Solr.
      get_url:
        url: "https://archive.apache.org/dist/lucene/solr/{{ solr_version }}/solr-{{ solr_version }}.tgz"
        dest: "{{ download_dir }}/solr-{{ solr_version }}.tgz"
        checksum: "{{ solr_checksum }}"
      notify: Restart solr

    - name: Expand Solr.
      unarchive:
        src: "{{ download_dir }}/solr-{{ solr_version }}.tgz"
        dest: "{{ download_dir }}"
        remote_src: true
        creates: "{{ download_dir }}/solr-{{ solr_version }}/README.txt"

    - name: Run Solr installation script.
      command: >
        {{ download_dir }}/solr-{{ solr_version }}/bin/install_solr_service.sh
        {{ download_dir }}/solr-{{ solr_version }}.tgz
        -i /opt
        -d /var/solr
        -u solr
        -s solr
        -p 8983
        creates={{ solr_dir }}/bin/solr
    - name: Ensure solr is started and enabled on boot.
      service: name=solr state=started enabled=yes
      
    - name: Ensure NTP is installed.
      yum: name=ntp state=present
    #- commend: echo Hello World
    #- shell: echo Nihaoma
    - name: Ensure NTP is running.
      service: name=ntpd state=started enabled=yes
    
    - name: Install Apache
      command: yum install -y --quiet httpd httpd-devel

    - name: Install Apache
      yum: 
        name:
          - httpd
          - httpd-devel
        state: present

    - name: Copy configuration files.
      command: cp /etc/httpd/conf/httpd.conf httpd.conf
    #- command: cp httpd-vhosts.conf /etc/httpd/conf/httpd-vhosts.conf

    - name: Copy configuration files.
      copy:
        src: "{{ item.src }}" # or, "{{ item['src'] }}"
        dest: "{{ item.dest }}"
        remote_src: yes
        owner: root
        group: root
        mode: 0644
      with_items:
        - dest: httpd.conf
          src: /etc/httpd/conf/httpd.conf
        #- src: httpd-vhosts.conf
        #  dest: /etc/httpd/conf/httpd-vhosts.conf

    - name: Start Apache and configure it to run at boot
      command: service httpd start

    - name: Start Apache and configure it to run at boot
      service: 
        name: httpd
        state: started
        enabled: true # or ... (yes), either way. Use 0/1 may get datatype mismatch error
        
    - command: chkconfig httpd on

