
    - name: Install Apache
      command: yum install -y --quiet httpd httpd-devel
      notify: Handler two

    - name: Flush Handlers
      meta: flush_handlers

    - name: Install Apache
      notify: Handler one
      yum: 
        name:
          - httpd
          - httpd-devel
        state: present

    - name: Flush Handlers
      meta: flush_handlers

    - name: Copy configuration files.
      command: cp /etc/httpd/conf/httpd.conf httpd.conf
      notify: Handler two
    #- command: cp httpd-vhosts.conf /etc/httpd/conf/httpd-vhosts.conf

    - name: Flush Handlers
      meta: flush_handlers

    - name: Copy configuration files.
      notify: Handler one
      copy:
        src: "{{ item.src }}" # or, "{{ item['src'] }}"
        dest: "{{ item.dest }}"
        remote_src: yes
        owner: root
        group: root
        mode: 0644
      with_items:
        - dest: httpd.conf
          src: /etc/httpd/conf/httpd.conf
        #- src: httpd-vhosts.conf
        #  dest: /etc/httpd/conf/httpd-vhosts.conf

    - name: Flush Handlers
      meta: flush_handlers

    - name: Start Apache and configure it to run at boot
      command: service httpd start
      notify: Handler two

    - name: Flush Handlers
      meta: flush_handlers

    - name: Start Apache and configure it to run at boot
      notify: Handler one
      service: 
        name: httpd
        state: started
        enabled: true # or ... (yes), either way. Use 0/1 may get datatype mismatch error

    - name: Flush Handlers
      meta: flush_handlers
        
    - command: chkconfig httpd on
      notify: Handler two

    - name: Flush Handlers
      meta: flush_handlers

    - name: Print content of httpd.conf
      command: cat httpd.conf
    
    # If the regexp does not match any line, then the file is not changed. If the regexp matches a line/multiple lines, then the last matched line will be replaced. 
    - name: Find and Replace or Append one line in/to httpd.conf
      lineinfile:
        dest: httpd.conf
        regexp: '^# .*'
        line: "Freddie is the best"
      
      register: findAndReplaceOrAppendOneLine # save this whole task to a variable 'findAndReplaceOrAppendOneLine'

    - debug: 
        var: findAndReplaceOrAppendOneLine # the variable/task (findAndReplaceOrAppendOneLine) that is going to print/debug